spring.application.name=botica-salud-ica
server.port=8080

# Clave de demostración Base64 de 256 bits.
# En producción debe definirse como variable de entorno JWT_SECRET.
app.jwt.secret=${JWT_SECRET:SaCOQcsHZOO7zidQ7IKu0aqSKRsT88+79MPQ5IrkpwY=}
